CREATE SCHEMA IF NOT EXISTS LOCADORA_DE_CARRO DEFAULT CHARACTER SET utf8 ;
USE LOCADORA_DE_CARRO ;
CREATE TABLE IF NOT EXISTS FILIAL (
  IDFILIAL INT NOT NULL,
  NOME VARCHAR(20) NULL,
  CIDADE VARCHAR(15) NOT NULL,
  UF VARCHAR(2) NOT NULL,
  PRIMARY KEY (IDFILIAL))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS CATEGORIA (
  IDCATEGORIA INT NOT NULL,
  NOME VARCHAR(20) NOT NULL,
  DESCRICAO VARCHAR(150) NOT NULL,
  VALORDIARIAPADRAO DECIMAL(10) NOT NULL,
  PRIMARY KEY (IDCATEGORIA))
ENGINE = InnoDB;

ALTER TABLE categoria
MODIFY COLUMN valorDiariaPadrao DECIMAL(10,2) NOT NULL;

CREATE TABLE IF NOT EXISTS CLIENTE (
  IDCLIENTE INT NOT NULL,
  NOME VARCHAR(40) NOT NULL,
  CPF VARCHAR(11) NOT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  TELEFONE VARCHAR(11) NOT NULL,
  DATACADASTRO DATETIME NOT NULL,
  PRIMARY KEY (IDCLIENTE))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS FUNCIONARIO (
  IDFUNCIONARIO INT NOT NULL,
  NOME VARCHAR(40) NOT NULL,
  CPF VARCHAR(11) NOT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  FILIAL_IDFILIAL INT NOT NULL,
  PRIMARY KEY (IDFUNCIONARIO, FILIAL_IDFILIAL),
  INDEX fk_FUNCIONARIO_FILIAL_idx (FILIAL_IDFILIAL ASC) VISIBLE,
  CONSTRAINT fk_FUNCIONARIO_FILIAL
    FOREIGN KEY (FILIAL_IDFILIAL)
    REFERENCES LOCADORA_DE_CARRO.FILIAL (IDFILIAL)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- aumenta tamanho de email em funcionario
ALTER TABLE funcionario
MODIFY COLUMN email VARCHAR(40);


CREATE TABLE IF NOT EXISTS VEICULO (
  IDVEICULO INT NOT NULL,
  PLACA VARCHAR(7) NOT NULL,
  RENAVAM VARCHAR(11) NOT NULL,
  MARCA VARCHAR(20) NOT NULL,
  MODELO VARCHAR(20) NOT NULL,
  ANO INT NOT NULL,
  FILIAL_IDFILIAL INT NOT NULL,
  CATEGORIA_IDCATEGORIA INT NOT NULL,
  PRIMARY KEY (IDVEICULO, FILIAL_IDFILIAL, CATEGORIA_IDCATEGORIA),
  INDEX fk_VEICULO_FILIAL1_idx (FILIAL_IDFILIAL ASC) VISIBLE,
  INDEX fk_VEICULO_CATEGORIA1_idx (CATEGORIA_IDCATEGORIA ASC) VISIBLE,
  CONSTRAINT fk_VEICULO_FILIAL1
    FOREIGN KEY (FILIAL_IDFILIAL)
    REFERENCES LOCADORA_DE_CARRO.FILIAL (IDFILIAL)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_VEICULO_CATEGORIA1
    FOREIGN KEY (CATEGORIA_IDCATEGORIA)
    REFERENCES LOCADORA_DE_CARRO.CATEGORIA (IDCATEGORIA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- adiciona kmAtual em veiculo para controle de quilometragem
ALTER TABLE veiculo
ADD COLUMN kmAtual INT DEFAULT NULL;


CREATE TABLE IF NOT EXISTS RESERVA (
  IDRESERVA INT NOT NULL,
  DATAINICIOPREV DATE NOT NULL,
  DATAFIMPREV DATE NOT NULL,
  IDFILIAL_DEVOLUCAO INT NOT NULL,
  IDFILIAL_RETIRADA INT NOT NULL,
  CLIENTE_IDCLIENTE INT NOT NULL,
  VEICULO_IDVEICULO INT NOT NULL,
  PRIMARY KEY (IDRESERVA, IDFILIAL_DEVOLUCAO, IDFILIAL_RETIRADA, CLIENTE_IDCLIENTE, VEICULO_IDVEICULO),
  INDEX fk_RESERVA_FILIAL1_idx (IDFILIAL_DEVOLUCAO ASC) VISIBLE,
  INDEX fk_RESERVA_CLIENTE1_idx (CLIENTE_IDCLIENTE ASC) VISIBLE,
  INDEX fk_RESERVA_VEICULO1_idx (VEICULO_IDVEICULO ASC, IDFILIAL_RETIRADA ASC) VISIBLE,
  CONSTRAINT fk_RESERVA_FILIAL1
    FOREIGN KEY (IDFILIAL_DEVOLUCAO)
    REFERENCES LOCADORA_DE_CARRO.FILIAL (IDFILIAL)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_RESERVA_CLIENTE1
    FOREIGN KEY (CLIENTE_IDCLIENTE)
    REFERENCES LOCADORA_DE_CARRO.CLIENTE (IDCLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_RESERVA_VEICULO1
    FOREIGN KEY (VEICULO_IDVEICULO , IDFILIAL_RETIRADA)
    REFERENCES LOCADORA_DE_CARRO.VEICULO (IDVEICULO , FILIAL_IDFILIAL)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS LOCADORA_DE_CARRO.LOCACAO (
  IDLOCACAO INT NOT NULL,
  DATARETIRADA DATETIME NOT NULL,
  KMRETIRADO INT NOT NULL,
  DATADEVOLUCAO DATETIME NOT NULL,
  KMDEVOLUCAO INT NOT NULL,
  VALORDIARIA DECIMAL(10) NOT NULL,
  TAXAS DECIMAL(10) NOT NULL,
  MULTA DECIMAL(10) NOT NULL,
  VALORFINAL DECIMAL(10) NOT NULL,
  RESERVA_IDRESERVA INT NOT NULL,
  CLIENTE_IDCLIENTE INT NOT NULL,
  VEICULO_IDVEICULO INT NOT NULL,
  IDFILIAL_RETIRADA INT NOT NULL,
  IDFILIAL_DEVOLUCAO INT NOT NULL,
  PRIMARY KEY (IDLOCACAO, RESERVA_IDRESERVA, CLIENTE_IDCLIENTE, VEICULO_IDVEICULO, IDFILIAL_RETIRADA, IDFILIAL_DEVOLUCAO),
  INDEX fk_LOCACAO_RESERVA1_idx (RESERVA_IDRESERVA ASC) VISIBLE,
  INDEX fk_LOCACAO_CLIENTE1_idx (CLIENTE_IDCLIENTE ASC) VISIBLE,
  INDEX fk_LOCACAO_VEICULO1_idx (VEICULO_IDVEICULO ASC) VISIBLE,
  INDEX fk_LOCACAO_FILIAL1_idx (IDFILIAL_RETIRADA ASC) VISIBLE,
  INDEX fk_LOCACAO_FILIAL2_idx (IDFILIAL_DEVOLUCAO ASC) VISIBLE,
  CONSTRAINT fk_LOCACAO_RESERVA1
    FOREIGN KEY (RESERVA_IDRESERVA)
    REFERENCES LOCADORA_DE_CARRO.RESERVA (IDRESERVA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_LOCACAO_CLIENTE1
    FOREIGN KEY (CLIENTE_IDCLIENTE)
    REFERENCES LOCADORA_DE_CARRO.CLIENTE (IDCLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_LOCACAO_VEICULO1
    FOREIGN KEY (VEICULO_IDVEICULO)
    REFERENCES LOCADORA_DE_CARRO.VEICULO (IDVEICULO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_LOCACAO_FILIAL1
    FOREIGN KEY (IDFILIAL_RETIRADA)
    REFERENCES LOCADORA_DE_CARRO.FILIAL (IDFILIAL)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_LOCACAO_FILIAL2
    FOREIGN KEY (IDFILIAL_DEVOLUCAO)
    REFERENCES LOCADORA_DE_CARRO.FILIAL (IDFILIAL)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
